#include "font-config.h"

#define COMPS_SP_SHOW 0

#define COMPS_SP_W 400
#define COMPS_SP_H 480

#define COMPS_SP_RADIUS (min(COMPS_SP_W, COMPS_SP_H)/2)
#define COMPS_SP_SCALE_S_GAP 6
#define COMPS_SP_SCALE_B_GAP 30
#define COMPS_SP_SCALE_S_LEN (COMPS_SP_RADIUS * 0.05)
#define COMPS_SP_SCALE_B_LEN (COMPS_SP_RADIUS * 0.12)

#define COMPS_TEXT_SP_W (COMPS_SP_RADIUS * 0.32)
#define COMPS_TEXT_SP_H (COMPS_SP_RADIUS * 0.15)

#define COMPS_MID_TEXT_SP_W (COMPS_SP_RADIUS /2)
#define COMPS_MID_TEXT_SP_H (COMPS_SP_RADIUS /2)
#define COMPS_MID_POINTER_SP_W (COMPS_SP_RADIUS/4)
#define COMPS_MID_POINTER_SP_H ((COMPS_SP_RADIUS) * 1.35)

#define COMPS_SP_BG_COLOR DARKGREY
#define COMPS_SP_SCALE_COLOR GREEN
#define COMPS_SP_TEXT_COLOR  GREEN
#define COMPS_SP_MID_BG_COLOR  DARKGREY
#define COMPS_SP_MID_TEXT_COLOR  MAGENTA

#define COMPS_MID_POINTER_UP_COLOR RED
#define COMPS_MID_POINTER_DOWN_COLOR WHITE

#define COMPASS_USED_FONT (min(COMPS_SP_W, COMPS_SP_H)/100)//240=2，

